baseURL = "https://asindu.drileba.capital/"			# Site's URL
title = "Asindu's Blog"								# Site's Name
theme = "manis"
copyright = "&copy; 2018 Asindu Drileba"	# Copyright notice. Note: You can use HTML tag here
pluralizeListTitles = false
paginate = 50								# Minimum number of item before paginate navigation show up
canonifyURL = true
disqusShortname = ""                        # Your disqus shortname
publishDir = "docs"

[taxonomies]
	tag = "tags"


[params]
	debugCSS = false                        # If false, use minified CSS (ui.min.css)
	disqusSections = ["blog"]               # list of section support disqus comments
	# Site meta description
	description = "Sweet little Hugo's theme for personal website or blog."
	tagline = "Synchronising Life and Dreams"   # Site's Tagline (Subtitle or Keyword)
	themeAttrib = true                      # If true give attribution to this theme
	licenseURL = "/about/license"           # URL to license file, can be outside of your domain

	# 404 Configuration
	head404 = "Error 404 Sorry, I can find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	colorTheme = "#008080"                  # Color of your website
	latestCount = 3                         # Maximum number of item in Latest Posts or Works
	faviconImg = "avatar.png"                         # Path to site's favicon image
	dateFmt = "Jan 02, 2006"                # Date format in item list

	# Code Highlighting (HighlightJS)
	highlightJs = true
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "asindu@drileba.capital"
	github = "https://github.com/as1ndu/"
	twitter = "https://twitter.com/as1ndu"


# Language Configuration
defaultContentLanguage = "en"
# Edit this if you want to translate your blog
#[languages.in]
#	lang = "in"
#	languageName = "Bahasa Indonesia"
#	weight = 1
