baseurl = "https://asindu.drileba.capital/"
title = "Synchronising Life & Dreams"
author = "as1ndu"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
publishDir = "docs"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Synchronising Life & Dreams."

[permalinks]
  post = "/:year/:month/:slug"

[[menu.main]]
    name = "@as1ndu"
    url  = "https://twitter.com/as1ndu"

languageCode = "en-us"
copyright = "Copyright (C) 2019 Asindu Willfred Drileba. All rights reserved."
