baseurl = "https://asindu.drileba.capital/"
title = "Synchronising Life & Dreams"
author = "as1ndu"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
publishDir = "docs"

pygmentsstyle       = "monokai"
pygmentscodefences  = true
# pygmentOptions = "linenos=table"


[params]
  sitename = "Synchronising Life & Dreams."
  description = "as1ndu's blog"

[permalinks]
  post = "/:year/:month/:slug"

[[menu.main]]
    name = "@as1ndu"
    url  = "https://twitter.com/as1ndu"


languageCode = "en-us"
copyright = "Copyright (C) 2019 Asindu Willfred Drileba. Permission to redistribute without alteration hereby granted."

