baseurl = "https://as1ndu.github.io/"
title = "Synchronising Life & Dreams"
author = "as1ndu"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
publishDir = "docs"

pygmentsstyle       = "monokai"
pygmentscodefences  = true
# pygmentOptions = "linenos=table"



[params]
  sitename = "Synchronising Life & Dreams"
  description = "Interested In Fintech & Machine Intelligence"
  blogRepository = "as1ndu/as1ndu.github.io"
  blogHeader = " “You never change things by fighting the existing reality. To change something, build a new model that makes the existing model obsolete.”  ― R. Buckminster Fuller"


[permalinks]
  post = "/:year/:month/:slug"

[[menu.main]]
    name = "@as1ndu"
    url  = "https://twitter.com/as1ndu"

languageCode = "en-us"
copyright = "Copyright (C) 2019 Asindu Willfred Drileba. Permission to redistribute without alteration hereby granted."

