baseurl = "https://as1ndu.xyz/"
title = "Asindu's journal"
author = "as1ndu"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
publishDir = "docs"
disqusShortname = "synchronising-life-and-dreams"
# pygmentsstyle       = "monokai"
# pygmentscodefences  = true
# pygmentOptions = "linenos=table"

[params]
  sitename = "Asindu's journal"
  description = "Interested In Fintech & Machine Intelligence"
  blogHeader = " “To change something, build a new model that makes the existing model obsolete.”  ― R. Buckminster Fuller"
  maxPosts = 3

[permalinks]
  posts = "/:year/:month/:slug"

[[menu.main]]
    name = "git"
    url  = "https://github.com/as1ndu"

[[menu.main]]
    name = "@as1ndu"
    url  = "https://twitter.com/as1ndu"

[[menu.main]]
    name = "rss"
    url  = "/index.xml"

languageCode = "en-us"
copyright = "Copyright (C) 2019 Asindu. Permission to redistribute without alteration hereby granted."

